# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Simultaneos Entropy Balancer
#' @description This function performs simultaneous entropy balancing on a set of samples across multiple zones, i.e., 2D balancing.
#' @param incidence A matrix of incidence values with dimensions (control_count × sample_count).
#' @param sub_weights A matrix of weights with dimensions (zone_count × sample_count) (mutable).
#' @param sub_controls A matrix of control values with dimensions (zone_count × control_count).
#' @param parent_controls A vector of parent control values with length (control_count).
#' @param parent_weights A vector of parent weights with length (sample_count).
#' @param weights_lb A vector of lower bounds for weights with length (sample_count).
#' @param weights_ub A vector of upper bounds for weights with length (sample_count).
#' @param controls_importance A vector of importance values for each control with length (control_count).
#' @param master_control_index An integer index for the master control, -1 means no master control.
#' @param max_iterations An integer specifying the maximum number of iterations to perform.
#' @param max_delta A double specifying the maximum allowed change in weights for convergence.
#' @param print_every_n An integer specifying how often to print progress information.
#' @return A list containing the updated weights, relaxation matrix, convergence status, number of iterations, delta, max gamma difference, and elapsed time.
#' @export
simul_entropy_balancer <- function(incidence, sub_weights, sub_controls, parent_controls, parent_weights, weights_lb, weights_ub, controls_importance, master_control_index = -1L, max_iterations = 10000L, max_delta = 1e-8, print_every_n = 10L) {
    .Call(`_rentropy_simul_entropy_balancer`, incidence, sub_weights, sub_controls, parent_controls, parent_weights, weights_lb, weights_ub, controls_importance, master_control_index, max_iterations, max_delta, print_every_n)
}

#' @title Entropy Balancer
#' @description Perform entropy balancing on a given incidence matrix with specified control totals and weights.
#' @param incidence Numeric matrix of incidence data (samples x controls).
#' @param initial_weights Numeric vector of initial weights for each sample.
#' @param control_totals Numeric vector of target totals for each control.
#' @param weights_lb Numeric vector of lower bounds for weights (optional).
#' @param weights_ub Numeric vector of upper bounds for weights (optional).
#' @param controls_importance Numeric vector of importance weights for each control (optional).
#' @param master_control_index Integer index of the master control (optional, default -1).
#' @param max_iterations Maximum number of iterations to run (default 10000).
#' @param max_delta Maximum allowed change in weights for convergence (default 1e-9).
#' @param print_every_n Print progress every n iterations (default 10).
#' @return A list containing the final weights, relaxation factors, convergence status, number of iterations, delta, and max gamma difference.
#' @export
entropy_balancer <- function(incidence, initial_weights, control_totals, weights_lb = as.numeric( c()), weights_ub = as.numeric( c()), controls_importance = as.numeric( c()), master_control_index = -1L, max_iterations = 10000L, max_delta = 1e-8, print_every_n = 10L) {
    .Call(`_rentropy_entropy_balancer`, incidence, initial_weights, control_totals, weights_lb, weights_ub, controls_importance, master_control_index, max_iterations, max_delta, print_every_n)
}

